# Generated by Django 4.2 on 2025-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['user', 'created_at'], name='assessments_user_id_abf42a_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['user', 'title'], name='assessments_user_id_078d58_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['title', 'created_at'], name='assessments_title_99a2b6_idx'),
        ),
    ]
